config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  mount Resque::Server.new, at: "/resque"
  
  resources :access_log_stats, only: [ :index]

  scope '/access_log_stats' do
    get 'run' => 'access_log_stats#run',  as: 'access_log_stats_run'
  end

end

app/models/access_log_status_stat.rb
class AccessLogStatusStat < ActiveRecord::Base

  scope :find_4xx_statuses, -> { where('status >= :min and status < :max_ex', { min: 400, max_ex: 500 }).order('count desc') }
  scope :find_5xx_statuses, -> { where('status >= :min and status < :max_ex', { min: 500, max_ex: 600 }).order('count desc') }

end

app/controllers/access_log_stats_controller.rb
class AccessLogStatsController < ApplicationController
 def index
    @access_log_stats_4xx = AccessLogStatusStat.find_4xx_statuses
    @access_log_stats_5xx = AccessLogStatusStat.find_5xx_statuses
  end

  def run
      @status = :ok
    begin
      Resque.enqueue(AccessLogStatusStatsJob, 0)
    rescue Exception => e
      logger.error "#{e.message} #{e.backtrace.join("\n")}"
      @status = :internal_server_error
    end

    respond_to do |format|
      format.json { render layout: false, status: @status }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/access_log_stats_helper.rb
module AccessLogStatsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/access_log_stats/_access_log_stats_list.haml
- if access_log_stats.size > 0
  %table
    %tbody
      %tr
        %th Host
        %th HTTP status code
        %th Request
        %th Hits
      - access_log_stats.each do |statistic|
        %tr
          %td= statistic.host
          %td= statistic.status
          %td= statistic.request
          %td= statistic.count

app/views/access_log_stats/index.haml
%h2 Access log statistics
= link_to 'Launch analysis', access_log_stats_run_path, remote: true, id: 'job-launcher'
|
= link_to 'Jobs statuses', '/resque', target: '_blank'
%h3#stats-4xx-header Statistics for 4xx statuses
#stats-4xx-box
  = render partial: 'access_log_stats_list', locals: { access_log_stats: @access_log_stats_4xx}
%h3#stats-5xx-header Statistics for 5xx statuses
#stats-5xx-box
  = render partial: 'access_log_stats_list', locals: { access_log_stats: @access_log_stats_5xx}

:javascript
  $("#stats-4xx-header").click(function() {
    $("#stats-4xx-box").toggle();
  })
  $("#stats-5xx-header").click(function() {
    $("#stats-5xx-box").toggle();
  })
  $("#job-launcher")
    .on('ajax:success', function(evt, data, xhr, status) {
    alert(data.msg);
    })
    .on('ajax:error', function(evt, xhr, status) {
      var json = $.parseJSON(xhr.responseText);
      alert(json.msg);
    })

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrestoResque</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>